/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 *
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 *
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 *
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 *
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 */
export interface IdentifyGroupRequestBody {
    identifier: string;
    properties: Record<string, unknown>;
}
