/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";

export const IdentifyUserRequestBodyGroupsItem: core.serialization.ObjectSchema<
    serializers.IdentifyUserRequestBodyGroupsItem.Raw,
    DoptApi.IdentifyUserRequestBodyGroupsItem
> = core.serialization.object({
    identifier: core.serialization.string(),
    properties: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace IdentifyUserRequestBodyGroupsItem {
    interface Raw {
        identifier: string;
        properties: Record<string, unknown>;
    }
}
