/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../..";

/**
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 *
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 *
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 *
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 *
 * @example
 *     {
 *         identifier: "identifier",
 *         properties: {}
 *     }
 */
export interface IdentifyUserRequestBody {
    identifier: string;
    properties: Record<string, unknown>;
    groups?: DoptApi.IdentifyUserRequestBodyGroupsItem[];
}
